### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ochorocho** [ochorocho/tdk-gitpod-addon#1]
- [ ] Allow to select TDK version
- [ ] Better message for Addon if no patch detected when on review.typo3.org
- [ ] pre select php version depending on patch?
